myapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from django.conf import settings

from webapp import views, classviews

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/$',classviews.UserFormView.as_view(),name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/login/'}),
    url(r'^tours/',include("webapp.urls")),
]


if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.conf.urls import url
from webapp import classviews

urlpatterns=[
        url(r'^display/$',classviews.Toursview.as_view(),name="toursdisplay"),
        url(r'^display/(?P<pk>[0-9]+)/$',classviews.ToursDetails.as_view(),name="toursdetails"),
        url(r'^create/$',classviews.Tourscreate.as_view(),name="tourscreate"),
        url(r'^display/update/(?P<pk>[0-9]+)/$',classviews.ToursUpdate.as_view(),name='tourupdate'),
        url(r'^display/(?P<pk>[0-9]+)/delete/$',classviews.ToursDelete.as_view(),name='tourdelete'),
        url(r'^display/(?P<pk>[0-9]+)/pictures/create/$',classviews.PicturesCreate.as_view(),name='picurescreate'),
        url(r'^display/(?P<tour_id>[0-9]+)/picturedelete/(?P<pk>[0-9]+)/$',classviews.PictureDelete.as_view(),name='picturedelete'),
]

webapp/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
from django.db.models.deletion import CASCADE


class Tour(models.Model):
    date= models.DateField()
    location=models.CharField(max_length=20)
    details=models.FileField()
    owner = models.ForeignKey(User)

    def get_absolute_url(self):
        return reverse('toursdetails',kwargs={'pk':self.pk})


    def __str__(self):
        return str(self.date)


class Picture(models.Model):
    name=models.CharField(max_length=20)
    tour=models.ForeignKey(Tour,on_delete=CASCADE)
    pic = models.ImageField()
    owner = models.ForeignKey(User)

    def __str__(self):
        return str(self.name)


#logout html page
#user registration form
#manual form
#create picture without taking tour manually
#files must beuploaded to a userfolder....and pictures to corresponding tours folder

webapp/forms.py
from django import forms
from django.contrib.auth.models import User

from webapp.models import Picture


class PictureCreateForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields=['name','pic']
        exclude=('tour',)


class UserForm(forms.ModelForm):
    password= forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model=User
        fields=['username','email','password']


webapp/views.py
from django.http import HttpResponse
# Create your views here.

templates/webapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'webapp/style.css' %}"/>

</head>
<body>

<h1>Travel Diaries <span class="glyphicon glyphicon-send"></span></h1>

<hr>
    {% block nav %}
        {% if user.is_authenticated %}
            <p align="right">
            <a href="{% url 'toursdisplay' %}" >Tours</a>


            <a href="{% url 'django.contrib.auth.views.logout' %}" class="logout" ><span class="glyphicon glyphicon-off"></span> Log out</a>
            </p>
        {% else %}
            <p align="right">
            <a href="{% url 'django.contrib.auth.views.login' %}" align="right">Login</a>
            </p>
        {% endif %}
        <hr>
    {% endblock %}


    {% block content %}{% endblock %}


</body>
</html>

templates/webapp/picture_confirm_delete.html
{% extends "webapp/base.html" %}
{% block title %}Delete Picture{% endblock %}


{% block content %}
    <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Delete" class="deletebutton"/>
    </form>
    <br>
    <a href="{% url 'toursdetails' picture.tour.id %}">cancel</a>
{% endblock %}

templates/webapp/picture_form.html
{% extends "webapp/base.html" %}
{% block title %}Add Picture{% endblock %}


{% block content %}
    <h2>Add Picture <span class="glyphicon glyphicon-camera"></span></h2>
    <br>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table> {{ form.as_table }}</table>


    <br>
            <input type="submit" value="submit" class="greenbutton"/>

    </form>
{% endblock %}



templates/webapp/registration_form.html
{% extends "webapp/base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <h2>Register</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table> {{ form.as_table }}</table>
            <input type="submit" value="submit" class="greenbutton"/>
    </form>
{% endblock %}


templates/webapp/tour_confirm_delete.html
{% extends "webapp/base.html" %}

{% block title %}Delete Tour{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Delete" class="deletebutton"/>
    </form>
    <br>
    <a href="{% url 'toursdetails' tour.id %}">cancel</a>
{% endblock %}

templates/webapp/tour_detail.html

{% extends "webapp/base.html" %}

{% block title %}Tour Details{% endblock %}


{% block content %}
    <h2>Tour Memories</h2>
    <p align="right">
    <a href="{% url 'tourupdate' tour.id %}">update tour</a>
    <a href="{% url 'tourdelete' tour.id %}" class="deletebutton">delete tour</a>
    </p>
    <table class="details">
    <tr><th align="left" >Tour Date</th><th> : </th></th><th align ="left"> {{ tour.date }}</th></tr>
    <tr><th align="left">Tour Location</th><th> : </th></th><th align ="left"> {{ tour.location }}</th></tr>
    <tr><th align="left">Tour Details</th><th> : </th></th><th align ="left"> <a href="{{ tour.details.url }}" class="notes">notes <span class="glyphicon glyphicon-file"></span></a></th></tr>
    </table>

<br>
    <h3>Images of Tour <span class="glyphicon glyphicon-picture"></span></h3>
    <p align="right"><a href="{% url 'picurescreate' tour.id %}">
    <span class="glyphicon glyphicon-plus-sign"></span> add picture</a></p>


    {% if not tour.picture_set.all %}

        <p class="colorred">you can add pictures related to this tour by clicking on add pictures</p>

    {% endif %}


    {% for image in tour.picture_set.all %}
        <div class="images">
        <div class="picname"><strong>{{ image.name }}</strong> <a href="{% url 'picturedelete' tour.id image.id %}" class="trashicon"><span class="glyphicon glyphicon-trash"></span></a></div>


        <img src="{{ image.pic.url }}" height="300" width="400">
        </div>
        <br>
        <br>
    {% endfor %}


{% endblock %}

templates/webapp/tour_form.html

{% extends "webapp/base.html" %}

{% block title %}Create Tour{% endblock %}

{% block content %}

    <h2>Create New Tour</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table> {{ form.as_table }}</table>
            <input type="submit" value="submit" class="greenbutton"/>
    </form>


{% endblock %}

templates/webapp/tour_list.html

{% extends "webapp/base.html" %}

{% block title %}Tour List{% endblock %}


{% block content %}

    <h2>List of Your Tours</h2>
    <p align="right">

    <a href="{% url 'tourscreate' %}">create tour</a>

    </p>

    {% if not tour_list %}
        <strong class="colorred">
    *you don't have any tours click on create tour to create
        </strong>
    {% endif %}

    <ol>
        {%  for o in tour_list %}
            <li><a href="{% url 'toursdetails' o.id %}">{{ o }}</a></li>
                <br>
        {%  endfor %}
    </ol>

{% endblock %}

templates/webapp/tour_update.html

{% extends "webapp/base.html" %}

{% block title %}Edit Tour{% endblock %}


{% block content %}
<h2>Edit Tour</h2>
<form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="update" class="greenbutton"/>
</form>

{% endblock %}